spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/timer
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        connection:
          driver_class: org.postgresql.Driver
          url: jdbc:postgresql://localhost:5432/timer
          username: postgres
          password: 1234
        default_batch_fetch_size: 15
    open-in-view: false
    show-sql: false
